In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [7]:
sales = pd.read_csv("../data/raw/sales_daily_final.csv")
sku = pd.read_csv("../data/raw/sku_master_final.csv")
calendar = pd.read_csv("../data/raw/calendar_final.csv")
inventory = pd.read_csv("../data/raw/inventory_snapshots_final.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [8]:
print("Sales Dataset:", sales.shape)
print("SKU Dataset:", sku.shape)
print("Calendar Dataset:", calendar.shape)
print("Inventory Dataset:", inventory.shape)

Sales Dataset: (573900, 6)
SKU Dataset: (300, 16)
Calendar Dataset: (1969, 22)
Inventory Dataset: (573900, 16)

In [9]:
sales.head()

         date            sku_id  units_sold  revenue  unit_price  promo_flag
0  2011-01-29  FOODS_1_001_CA_1           3      6.0         2.0           1
1  2011-01-29  FOODS_1_001_CA_2           2      4.0         2.0           1
2  2011-01-29  FOODS_1_001_CA_3           1      2.0         2.0           1
3  2011-01-29  FOODS_1_001_CA_4           0      0.0         2.0           1
4  2011-01-29  FOODS_1_001_TX_1           0      0.0         2.0           1

In [10]:
sku.head()

,sku_id,item_id,category,subcategory,department,store_id,state_id,launch_date,first_sale_date,last_sale_date,product_age_days,avg_price,list_price,unit_cost,gross_margin,product_status
0,FOODS_1_001_CA_1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_1,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.17,2.24,1.57,0.67,Active
1,FOODS_1_001_CA_2,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_2,CA,2011-01-29,2011-01-29,2016-04-24,1912,2.17,2.24,1.57,0.67,Active
2,FOODS_1_001_CA_3,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_3,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.16,2.24,1.57,0.67,Active
3,FOODS_1_001_CA_4,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_4,CA,2011-01-30,2011-01-30,2016-04-24,1911,2.17,2.24,1.57,0.67,Active
4,FOODS_1_001_TX_1,FOODS_1_001,FOODS,Foods 1,FOODS_1,TX_1,TX,2011-01-30,2011-01-30,2016-04-05,1911,2.15,2.24,1.57,0.67,Active

In [11]:
calendar.head()

,date,d,wm_yr_wk,day_of_week,day_name,week_of_month,week_of_year,month,month_name,quarter,year,is_weekend,season,event_name_1,event_type_1,event_name_2,event_type_2,is_holiday,promo_event,snap_CA,snap_TX,snap_WI
0,2011-01-29,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
1,2011-01-30,d_2,11101,7,Sunday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
2,2011-01-31,d_3,11101,1,Monday,6,5,1,January,Q1,2011,0,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
3,2011-02-01,d_4,11101,2,Tuesday,1,5,2,February,Q1,2011,0,Winter,NaN,NaN,NaN,NaN,0,0,1,1,0
4,2011-02-02,d_5,11101,3,Wednesday,1,5,2,February,Q1,2011,0,Winter,NaN,NaN,NaN,NaN,0,0,1,0,1

In [12]:
inventory.head()

,date,sku_id,opening_stock,units_sold,fulfilled_units,lost_sales_units,received_stock,closing_stock,reorder_point,reorder_quantity,on_order_units,lead_time_days,target_stock,inventory_status,inventory_value,days_of_supply
0,2011-01-29,FOODS_1_001_CA_1,18,3,3,0,0,15,14,0,0,7,30,Healthy,23.55,19.09
1,2011-01-30,FOODS_1_001_CA_1,15,0,0,0,0,15,14,0,0,7,30,Healthy,23.55,19.09
2,2011-01-31,FOODS_1_001_CA_1,15,0,0,0,0,15,14,0,0,7,30,Healthy,23.55,19.09
3,2011-02-01,FOODS_1_001_CA_1,15,1,1,0,0,14,14,16,16,7,30,Low Stock,21.98,17.82
4,2011-02-02,FOODS_1_001_CA_1,14,4,4,0,0,10,14,0,16,7,30,Low Stock,15.70,12.73

In [13]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 573900 entries, 0 to 573899
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        573900 non-null  str
 1   sku_id      573900 non-null  str
 2   units_sold  573900 non-null  int64
 3   revenue     573900 non-null  float64
 4   unit_price  573900 non-null  float64
 5   promo_flag  573900 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 41.6 MB

In [14]:
sku.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sku_id            300 non-null    str
 1   item_id           300 non-null    str
 2   category          300 non-null    str
 3   subcategory       300 non-null    str
 4   department        300 non-null    str
 5   store_id          300 non-null    str
 6   state_id          300 non-null    str
 7   launch_date       300 non-null    str
 8   first_sale_date   300 non-null    str
 9   last_sale_date    300 non-null    str
 10  product_age_days  300 non-null    int64
 11  avg_price         300 non-null    float64
 12  list_price        300 non-null    float64
 13  unit_cost         300 non-null    float64
 14  gross_margin      300 non-null    float64
 15  product_status    300 non-null    str
dtypes: float64(4), int64(1), str(11)
memory usage: 66.4 KB

In [15]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1969 non-null   str
 1   d              1969 non-null   str
 2   wm_yr_wk       1969 non-null   int64
 3   day_of_week    1969 non-null   int64
 4   day_name       1969 non-null   str
 5   week_of_month  1969 non-null   int64
 6   week_of_year   1969 non-null   int64
 7   month          1969 non-null   int64
 8   month_name     1969 non-null   str
 9   quarter        1969 non-null   str
 10  year           1969 non-null   int64
 11  is_weekend     1969 non-null   int64
 12  season         1969 non-null   str
 13  event_name_1   162 non-null    str
 14  event_type_1   162 non-null    str
 15  event_name_2   5 non-null      str
 16  event_type_2   5 non-null      str
 17  is_holiday     1969 non-null   int64
 18  promo_event    1969 non-null   int64
 19  snap_CA        1969 non-null   int64
 20  snap_TX        1969 non-null   int64
 21  snap_WI        1969 non-null   int64
dtypes: int64(12), str(10)
memory usage: 413.2 KB

In [16]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 573900 entries, 0 to 573899
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   date              573900 non-null  str
 1   sku_id            573900 non-null  str
 2   opening_stock     573900 non-null  int64
 3   units_sold        573900 non-null  int64
 4   fulfilled_units   573900 non-null  int64
 5   lost_sales_units  573900 non-null  int64
 6   received_stock    573900 non-null  int64
 7   closing_stock     573900 non-null  int64
 8   reorder_point     573900 non-null  int64
 9   reorder_quantity  573900 non-null  int64
 10  on_order_units    573900 non-null  int64
 11  lead_time_days    573900 non-null  int64
 12  target_stock      573900 non-null  int64
 13  inventory_status  573900 non-null  str
 14  inventory_value   573900 non-null  float64
 15  days_of_supply    573900 non-null  float64
dtypes: float64(2), int64(11), str(3)
memory usage: 89.6 MB

In [17]:
sales.describe()

          units_sold        revenue     unit_price     promo_flag
count  573900.000000  573900.000000  573900.000000  573900.000000
mean        1.000056       2.997589       4.696462       0.485524
std         2.759531       6.908256       3.590448       0.499791
min         0.000000       0.000000       0.100000       0.000000
25%         0.000000       0.000000       2.240000       0.000000
50%         0.000000       0.000000       3.230000       0.000000
75%         1.000000       2.980000       6.710000       1.000000
max       116.000000     206.480000      17.970000       1.000000

In [18]:
inventory.describe()

,opening_stock,units_sold,fulfilled_units,lost_sales_units,received_stock,closing_stock,reorder_point,reorder_quantity,on_order_units,lead_time_days,target_stock,inventory_value,days_of_supply
count,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000,573900.000000
mean,22.766198,1.000056,0.972706,0.027350,0.963565,22.757057,16.476667,0.977045,6.561821,6.696667,37.463333,54.065371,31.368871
std,37.550837,2.759531,2.657457,0.673718,8.343796,37.521766,20.841390,8.375605,20.724883,2.256398,52.579845,61.991882,22.091278
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000
25%,7.000000,0.000000,0.000000,0.000000,0.000000,7.000000,6.000000,0.000000,0.000000,5.000000,12.000000,20.520000,18.940000
50%,13.000000,0.000000,0.000000,0.000000,0.000000,13.000000,10.000000,0.000000,0.000000,7.000000,20.500000,35.550000,27.160000
75%,23.000000,1.000000,1.000000,0.000000,0.000000,23.000000,17.000000,0.000000,4.000000,9.000000,38.000000,62.800000,38.260000
max,538.000000,116.000000,116.000000,80.000000,259.000000,538.000000,149.000000,259.000000,259.000000,10.000000,354.000000,737.060000,229.560000

In [19]:
sales.isnull().sum()

date          0
sku_id        0
units_sold    0
revenue       0
unit_price    0
promo_flag    0
dtype: int64

In [20]:
sku.isnull().sum()

sku_id              0
item_id             0
category            0
subcategory         0
department          0
store_id            0
state_id            0
launch_date         0
first_sale_date     0
last_sale_date      0
product_age_days    0
avg_price           0
list_price          0
unit_cost           0
gross_margin        0
product_status      0
dtype: int64

In [21]:
calendar.isnull().sum()
inventory.isnull().sum()

date                0
sku_id              0
opening_stock       0
units_sold          0
fulfilled_units     0
lost_sales_units    0
received_stock      0
closing_stock       0
reorder_point       0
reorder_quantity    0
on_order_units      0
lead_time_days      0
target_stock        0
inventory_status    0
inventory_value     0
days_of_supply      0
dtype: int64

In [22]:
print("Sales:", sales.duplicated().sum())
print("SKU:", sku.duplicated().sum())
print("Calendar:", calendar.duplicated().sum())
print("Inventory:", inventory.duplicated().sum())

Sales: 0
SKU: 0
Calendar: 0
Inventory: 0

In [23]:
sales["sku_id"].nunique()

300

In [24]:
sales_sku = pd.merge(
    sales,
    sku,
    on="sku_id",
    how="left"
)

print(sales_sku.shape)
sales_sku.head()

(573900, 21)

,date,sku_id,units_sold,revenue,unit_price,promo_flag,item_id,category,subcategory,department,store_id,state_id,launch_date,first_sale_date,last_sale_date,product_age_days,avg_price,list_price,unit_cost,gross_margin,product_status
0,2011-01-29,FOODS_1_001_CA_1,3,6.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_1,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.17,2.24,1.57,0.67,Active
1,2011-01-29,FOODS_1_001_CA_2,2,4.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_2,CA,2011-01-29,2011-01-29,2016-04-24,1912,2.17,2.24,1.57,0.67,Active
2,2011-01-29,FOODS_1_001_CA_3,1,2.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_3,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.16,2.24,1.57,0.67,Active
3,2011-01-29,FOODS_1_001_CA_4,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_4,CA,2011-01-30,2011-01-30,2016-04-24,1911,2.17,2.24,1.57,0.67,Active
4,2011-01-29,FOODS_1_001_TX_1,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,TX_1,TX,2011-01-30,2011-01-30,2016-04-05,1911,2.15,2.24,1.57,0.67,Active

In [25]:
sales_sku_calendar = pd.merge(
    sales_sku,
    calendar,
    on="date",
    how="left"
)

print(sales_sku_calendar.shape)
sales_sku_calendar.head()

(573900, 42)

,date,sku_id,units_sold,revenue,unit_price,promo_flag,item_id,category,subcategory,department,store_id,state_id,launch_date,first_sale_date,last_sale_date,product_age_days,avg_price,list_price,unit_cost,gross_margin,product_status,d,wm_yr_wk,day_of_week,day_name,week_of_month,week_of_year,month,month_name,quarter,year,is_weekend,season,event_name_1,event_type_1,event_name_2,event_type_2,is_holiday,promo_event,snap_CA,snap_TX,snap_WI
0,2011-01-29,FOODS_1_001_CA_1,3,6.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_1,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
1,2011-01-29,FOODS_1_001_CA_2,2,4.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_2,CA,2011-01-29,2011-01-29,2016-04-24,1912,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
2,2011-01-29,FOODS_1_001_CA_3,1,2.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_3,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.16,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
3,2011-01-29,FOODS_1_001_CA_4,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_4,CA,2011-01-30,2011-01-30,2016-04-24,1911,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
4,2011-01-29,FOODS_1_001_TX_1,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,TX_1,TX,2011-01-30,2011-01-30,2016-04-05,1911,2.15,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0

In [27]:
final_df = pd.merge(
    sales_sku_calendar,
    inventory,
    on=["date", "sku_id"],
    how="left",
    suffixes=("", "_inventory")
)

print(final_df.shape)

(573900, 56)

In [28]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573900 entries, 0 to 573899
Data columns (total 56 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   date                  573900 non-null  str
 1   sku_id                573900 non-null  str
 2   units_sold            573900 non-null  int64
 3   revenue               573900 non-null  float64
 4   unit_price            573900 non-null  float64
 5   promo_flag            573900 non-null  int64
 6   item_id               573900 non-null  str
 7   category              573900 non-null  str
 8   subcategory           573900 non-null  str
 9   department            573900 non-null  str
 10  store_id              573900 non-null  str
 11  state_id              573900 non-null  str
 12  launch_date           573900 non-null  str
 13  first_sale_date       573900 non-null  str
 14  last_sale_date        573900 non-null  str
 15  product_age_days      573900 non-null  int64
 16  avg_price             573900 non-null  float64
 17  list_price            573900 non-null  float64
 18  unit_cost             573900 non-null  float64
 19  gross_margin          573900 non-null  float64
 20  product_status        573900 non-null  str
 21  d                     573900 non-null  str
 22  wm_yr_wk              573900 non-null  int64
 23  day_of_week           573900 non-null  int64
 24  day_name              573900 non-null  str
 25  week_of_month         573900 non-null  int64
 26  week_of_year          573900 non-null  int64
 27  month                 573900 non-null  int64
 28  month_name            573900 non-null  str
 29  quarter               573900 non-null  str
 30  year                  573900 non-null  int64
 31  is_weekend            573900 non-null  int64
 32  season                573900 non-null  str
 33  event_name_1          46200 non-null   str
 34  event_type_1          46200 non-null   str
 35  event_name_2          1200 non-null    str
 36  event_type_2          1200 non-null    str
 37  is_holiday            573900 non-null  int64
 38  promo_event           573900 non-null  int64
 39  snap_CA               573900 non-null  int64
 40  snap_TX               573900 non-null  int64
 41  snap_WI               573900 non-null  int64
 42  opening_stock         573900 non-null  int64
 43  units_sold_inventory  573900 non-null  int64
 44  fulfilled_units       573900 non-null  int64
 45  lost_sales_units      573900 non-null  int64
 46  received_stock        573900 non-null  int64
 47  closing_stock         573900 non-null  int64
 48  reorder_point         573900 non-null  int64
 49  reorder_quantity      573900 non-null  int64
 50  on_order_units        573900 non-null  int64
 51  lead_time_days        573900 non-null  int64
 52  target_stock          573900 non-null  int64
 53  inventory_status      573900 non-null  str
 54  inventory_value       573900 non-null  float64
 55  days_of_supply        573900 non-null  float64
dtypes: float64(8), int64(26), str(22)
memory usage: 325.5 MB

In [29]:
final_df.head()

,date,sku_id,units_sold,revenue,unit_price,promo_flag,item_id,category,subcategory,department,store_id,state_id,launch_date,first_sale_date,last_sale_date,product_age_days,avg_price,list_price,unit_cost,gross_margin,product_status,d,wm_yr_wk,day_of_week,day_name,week_of_month,week_of_year,month,month_name,quarter,year,is_weekend,season,event_name_1,event_type_1,event_name_2,event_type_2,is_holiday,promo_event,snap_CA,snap_TX,snap_WI,opening_stock,units_sold_inventory,fulfilled_units,lost_sales_units,received_stock,closing_stock,reorder_point,reorder_quantity,on_order_units,lead_time_days,target_stock,inventory_status,inventory_value,days_of_supply
0,2011-01-29,FOODS_1_001_CA_1,3,6.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_1,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0,18,3,3,0,0,15,14,0,0,7,30,Healthy,23.55,19.09
1,2011-01-29,FOODS_1_001_CA_2,2,4.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_2,CA,2011-01-29,2011-01-29,2016-04-24,1912,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0,48,2,2,0,0,46,24,0,0,10,48,Healthy,72.22,39.75
2,2011-01-29,FOODS_1_001_CA_3,1,2.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_3,CA,2011-01-29,2011-01-29,2016-04-23,1912,2.16,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0,85,1,1,0,0,84,27,0,0,9,53,Overstock,131.88,69.81
3,2011-01-29,FOODS_1_001_CA_4,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,CA_4,CA,2011-01-30,2011-01-30,2016-04-24,1911,2.17,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0,19,0,0,0,0,19,7,0,0,5,15,Healthy,29.83,52.83
4,2011-01-29,FOODS_1_001_TX_1,0,0.0,2.0,1,FOODS_1_001,FOODS,Foods 1,FOODS_1,TX_1,TX,2011-01-30,2011-01-30,2016-04-05,1911,2.15,2.24,1.57,0.67,Active,d_1,11101,6,Saturday,5,4,1,January,Q1,2011,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0,26,0,0,0,0,26,14,0,0,8,26,Healthy,40.82,44.45

In [30]:
final_df.to_csv("../data/processed/final_cleaned_dataset.csv", index=False)

print("✅ Final cleaned dataset saved successfully!")

✅ Final cleaned dataset saved successfully!